config/routes.rb
Rails.application.routes.draw do

  root "categories#index"
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  get "/contact", to: "static_pages#contact"

  get "/admin", to: "admin/admins#index"
  get "/welcome", to: "client/clients#index"

  resources :users
  resources :products
  resources :categories

  namespace :admin do
    root "admins#index"
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  namespace :client do
    root "clients#index"
    resources :carts
    resources :orders, only: [:create, :index]
    resources :rates, only: :create
  end

end

app/controllers/client/carts_controller.rb
class Client::CartsController < ApplicationController
  before_action :current_order, only: %i(index create destroy)
  before_action :load_product, only: %i(create destroy)
  before_action :reload_cart, only: :index

  include MyModules::Carts

  def index; end

  def create
    if check_quantity_validation @product
      flash[:danger] = t "flash.out_of_index"
    elsif update_existed_item @product
      flash[:success] = t "added"
    else
      add_new_item @product
    end
    redirect_to products_path
  end

  def destroy
    update_after_deleting @product
    flash[:success] = t "success_delete"
    redirect_to client_carts_path
  end

  private

  def item_params
    params.require(:order_product).permit :product_id, :price, :quantity
  end

  def load_product
    id = params["id"] || item_params[:product_id]
    @product = Product.find_by id: id
    return if @product
    flash[:danger] = t "not_found_product"
    redirect_to products_path
  end

  def reload_cart
    @items = {}
    session[:cart].each do |key, value|
      item = {}
      load_product_from_cart key
      next unless @product
      item[:product] = @product
      item[:quantity] = value
      @items[key] = item
    end
    load_total_cost @items
  end

  def load_total_cost items
    @total = items.values.reduce(0) do |a, e|
      a + e[:product][:price] * e[:quantity]
    end
  end

  def load_product_from_cart key
    @product = Product.find_by id: key
    return if @product
    session[:cart].except!(key)
  end

  def check_quantity_validation product
    item_params[:quantity].to_i <= Settings.lowest_quantity ||
      product.quantity < item_params[:quantity].to_i
  end

  def update_existed_item product
    session[:cart].each do |key, value|
      next unless key.to_i == product.id
      session[:cart][key] = load_added_qty value, item_params[:quantity]
      remain_qty = load_remain_qty product.quantity, item_params[:quantity]
      return true if product.update_attribute :quantity, remain_qty
      flash[:danger] = t "flash.update_fail"
    end
    false
  end

  def add_new_item product
    session[:cart][product.id] = item_params[:quantity].to_i
    remain_qty = load_remain_qty product.quantity, item_params[:quantity]
    product.update_attribute :quantity, remain_qty
    flash[:success] = t "success_add"
  end

  def update_after_deleting product
    session[:cart].each do |key, value|
      next unless key == params[:id]
      added_quantity = load_added_qty product.quantity, value
      if product.update_attribute :quantity, added_quantity
        session[:cart].except!(key)
      else
        flash[:danger] = t "flash.delete_fail"
        redirect_to carts_path
      end
    end
  end
end

app/controllers/client/clients_controller.rb
class Client::ClientsController < ApplicationController
  before_action :user_permissions
  authorize_resource
  def index; end

  def user_permissions
    unless user_signed_in? && current_user.active?
      redirect_to root_path
    end
  end

  include Client::CartsHelper
end

app/controllers/client/orders_controller.rb
class Client::OrdersController < Client::ClientsController
  before_action :current_order, only: :create

  def index
    @orders = current_user.orders.order_by_created_time.page(params[:page]).per(
      Settings.paging_sm
    )
  end

  def create
    ActiveRecord::Base.transaction do
      create_order
      session[:cart].each do |key, value|
        load_product key
        create_order_product @product, value, @order.id
      end
      session[:cart].clear
      send_order @order
      flash[:success] = t "flash.ordered"
      redirect_to client_orders_path
    end
  rescue ActiveRecord::RecordInvalid
    flash[:warning] = t "flash.rescue_order_creating"
  end

  private

  def create_order
    @order = Order.create(user_id: current_user.id)
    return if @order.save
    flash[:danger] = t "flash.order_faild"
    redirect_to client_carts_path
  end

  def load_product key
    @product = Product.find_by id: key
    return if @product
    flash[:danger] = t "flash.no_longer_sold", name: @product.name
    redirect_to client_carts_path
  end

  def create_order_product product, quantity, order_id
    order_product = OrderProduct.new(
      product_id: product.id,
      quantity: quantity,
      price: product.price,
      order_id: order_id
    )
    return if order_product.save
    flash[:warning] = t "flash.cannot_save"
    redirect_to client_orders_path
  end

  def send_order order
    OrderMailer.new_order(current_admin, current_user, order).deliver_later
  end
end

app/controllers/client/rates_controller.rb
class Client::RatesController < Client::ClientsController
  def create
    @rate = Rate.new rate_params
    if @rate.save
      flash[:info] = t "flash.rate_success"
    else
      flash[:warning] = t "flash.rate_fail"
    end
    redirect_to product_path(params[:rate][:product_id])
  end

  private

  def rate_params
    params.require(:rate).permit :rate, :comment, :product_id, :user_id
  end
end

app/helpers/client/carts_helper.rb
module Client::CartsHelper
  def current_order
    session[:cart] ||= {}
  end
end

app/helpers/client/orders_helper.rb
module Client::OrdersHelper
  include MyModules::Orders
end

app/helpers/client/rates_helper.rb
module Client::RatesHelper
  include MyModules::Rates
  def is_allow_to_rate? product
    return false if !user_signed_in? ||
                    current_user.admin? ||
                    current_user.rates.find_by(product_id: product.id)
    current_user.orders.each do |order|
      next unless order.delivered?
      order.order_products.each do |order_product|
        return true if order_product.product_id == product.id
      end
    end
    false
  end
end

app/views/layouts/client/_banner.html.erb
<div class="slide fullscreen bg-image--1 show_banner">
  <button class="banner-close">
    <i class="zmdi zmdi-close"></i>
  </button>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="slider__content">
          <div class="slider__inner">
            <h2>“AAHAR”</h2>
            <h1>food delivery &amp; service</h1>
            <%= search_form_for @q do |f| %>
              <div class="slider__input">
                <%= f.text_field :name_cont, class: "", placeholder: "Type" %>

                <%= f.submit "Search", class: "src__btn res__search" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/client/_banner2.html.erb
<div class="ht__bradcaump__area bg-image--18">
  <div class="ht__bradcaump__wrap d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="bradcaump__inner text-center">
            <h2 class="bradcaump-title" style="color: white"></h2>
            <nav class="bradcaump-inner">
              <a class="breadcrumb-item" href="index.html"></a>
              <span class="brd-separetor">
                <i class="zmdi zmdi-long-arrow-right"></i>
              </span>
              <span class="breadcrumb-item active"></span>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/client/_cart.html.erb
  <div class="cartbox-wrap">
    <div class="cartbox text-right">
      <button class="cartbox-close">
        <i class="zmdi zmdi-close"></i>
      </button>
      <div class="cartbox__inner text-left">
        <div class="cartbox__items">
          No Item
          <% unless @items.size %>
            No Item
          <% end %>
          <% @items.each do |key, value| %>
            <div class="cartbox__item">
              <div class="cartbox__item__thumb">
                <a href="product-details.html">
                  <%= image_tag value[:product].picture.url %>
                </a>
              </div>
              <div class="cartbox__item__content">
                <h5>
                  <%= link_to products_path, class: "product-name" do %>
                    <%= value[:product].name %>
                  <% end %>
                </h5>
                <p>Qty:
                  <span><%= value[:quantity] %></span></p>
                <span class="price">$<%= value[:product].price %></span>
              </div>
              <button class="cartbox__item__remove">
                <i class="fa fa-trash"></i>
              </button>
            </div>
          <% end %>
        </div>
        <div class="cartbox__total">
          <ul>
            <li class="grandtotal">Total<span class="price">$<%= @total %></span></li>
          </ul>
        </div>
        <div class="cartbox__buttons">

          <a class="food__btn" href="/client/carts">
            <span>View cart</span></a>
          <%= link_to client_orders_path, method: :post, class: "food__btn",
            data: {confirm: t("carts.confirm_checkout")} do %>
            <span><%= t "order.order" %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/client/_client.html.erb
<div class="wrapper" id="wrapper">
  <%= render "layouts/client/header", drinks: @drinks, foods: @foods, items: @items %>
  <%= render "layouts/client/banner" %>
  <div class="">
    <%= yield %>
  </div>
  <%= render "layouts/client/footer" %>
  <%= render "layouts/client/login_form" %>
  <%= render "layouts/client/cart", items: @items %>
</div>

app/views/layouts/client/_client_application.html.erb
<!doctype html>
<html>
	<head>
		<title><%= full_title yield(:title) %></title>
		<%= render "layouts/client/head" %>
	</head>
	<body>
		<%= render "layouts/client/client" %>
	</body>
</html>

app/views/layouts/client/_confirmation_form.html.erb
<%= form_for(@user, as: :user, url: confirmation_path(:user), html: { method: :post }, remote: true) do |f| %>
  <div class="single-input">
    <h4><%= t "devise.confirm.confirm" %></h4>
  </div>
  <div id="reset_errors">
  </div>

  <div class="single-input">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: (resource.pending_reconfirmation? ? resource.unconfirmed_email : resource.email) %>
  </div>

  <div class="single-input">
    <%= f.submit "Resend confirmation instructions" %>
  </div>
<% end %>

app/views/layouts/client/_footer.html.erb
<footer class="footer__area footer--1">
  <div class="copyright bg--theme">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          <div class="copyright__inner">
            <div class="cpy__right--left">
              <p><%= t "layouts.footer.copywrite" %>
              </p>
            </div>
            <div class="cpy__right--right">
              <a href="#">
                <img src="/assets/icon/shape/2.png" alt="payment images">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/client/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="shortcut icon" href="/assets/favicon.ico">
<link rel="apple-touch-icon" href="/assets/icon.png">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>

app/views/layouts/client/_header.html.erb
<header class="htc__header bg--white">
  <div id="sticky-header-with-topbar" class="mainmenu__wrap sticky__header">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 col-sm-4 col-md-6 order-1 order-lg-1">
          <div class="logo">
            <a href="index.html">
              <img src="/assets/logo/foody.png" alt="logo images">
            </a>
          </div>
        </div>
        <div class="col-lg-9 col-sm-4 col-md-2 order-3 order-lg-2">
          <div class="main__menu__wrap">
            <nav class="main__menu__nav d-none d-lg-block">
              <ul class="mainmenu">
                <li class="drop">
                  <a href="index.html"><%= t "static_pages.home" %></a>
                </li>
                <li class="drop">
                  <a href="menu-list.html"><%= t "generals.food" %></a>
                  <ul class="dropdown__menu">
                    <% foods.map do |drink| %>
                      <li>
                        <%= link_to food.name, category_path(food) %>
                      </li>
                    <% end %>
                  </ul>
                </li>
                <li class="drop">
                  <a href="menu-list.html"><%= t "generals.drink" %></a>
                  <ul class="dropdown__menu">
                    <% drinks.map do |drink| %>
                      <li>
                        <%= link_to drink.name, category_path(drink) %>
                      </li>
                    <% end %>
                  </ul>
                </li>
                <% if can? :manange, Order %>
                  <li>
                    <a href="/client/orders"><%= t "generals.my_history" %></a>
                  </li>
                <% end %>
                <li>
                  <a href="gallery.html"><%= t "generals.suggestion" %></a>
                </li>
                <li>
                  <a href="contact.html"><%= t "static_pages.contact" %></a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <div class="col-lg-1 col-sm-4 col-md-4 order-2 order-lg-3">
          <div class="header__right d-flex justify-content-end">
            <% if user_signed_in? %>
              <div class="">
                <div class="main__menu__wrap">
                  <nav class="main__menu__nav d-none d-lg-block">
                    <ul class="mainmenu">
                      <li class="drop">
                        <% if can? :create, Order %>
                          <a class="" href="#">
                            <i class="zmdi zmdi-account-o"></i>
                          </a>
                        <% end %>
                        <ul class="dropdown__menu">
                          <li><%= link_to t("static_pages.profile"), admin_user_path(current_user) %></li>
                          <li><%= link_to t("static_pages.settings"), edit_user_path(current_user) %></li>
                          <li class="divider"></li>
                          <li>
                            <%= link_to t("static_pages.logout"), destroy_user_session_path, method: :delete %>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </nav>
                </div>
              </div>
            <% else %>
              <div class="log__in">
                <a class="accountbox-trigger" href="#">
                  <i class="zmdi zmdi-account-o"></i>
                </a>
              </div>
            <% end %>
            <% if user_signed_in? %>
              <div class="shopping__cart">
                <a class="minicart-trigger" href="#">
                  <i class="zmdi zmdi-shopping-basket"></i>
                </a>
                <div class="shop__qun">
                  <span><%= @items.size %></span>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="mobile-menu d-block d-lg-none"></div>
    </div>
  </div>
</header>

app/views/layouts/client/_login_form.html.erb
<div class="accountbox-wrapper">
  <div class="accountbox text-left">
    <ul class="nav accountbox__filters" id="myTab" role="tablist">
      <li>
        <a class="active" id="log-tab" data-toggle="tab" href="#log" role="tab" aria-controls="log" aria-selected="true">Login</a>
      </li>
      <li>
        <a id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Register</a>
      </li>
    </ul>
    <div class="accountbox__inner tab-content" id="myTabContent">
      <div class="accountbox__login tab-pane fade show active" id="log" role="tabpanel" aria-labelledby="log-tab">
        <%= form_for(:user, :url => session_path(:user)) do |f| %>
          <div class="single-input">
            <%= f.email_field :email, class: "cr-round--lg", placeholder: true %>
          </div>

          <div class="single-input">
            <%= f.password_field :password, class: "cr-round--lg", placeholder: true %>
          </div>

          <%= f.label :remember_me, class: "checkbox inline" do %>
            <%= f.check_box :remember_me %>
            <span><%= t "remember" %></span>
          <% end %>

          <div class="single-input">
            <%= f.submit t("layouts.header.title4"), class: "food__btn" %>
          </div>

          <div class="single-input">
            <%= link_to "Forgot your password?", new_password_path(:user), remote: true %><br />
          </div>
          <div class="single-input">
            <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(:user), remote: true %><br />
          </div>
        <% end %>
      </div>
      <div class="accountbox__register tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <%= render "layouts/client/signup_form" %>
      </div>
      <div class="accountbox__options tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <%= render "layouts/client/reset_password_form" %>
      </div>
      <span class="accountbox-close-button">
        <i class="zmdi zmdi-close"></i>
      </span>
    </div>
  </div>
</div>

app/views/layouts/client/_reset_password_form.html.erb
<%= form_for(@user, as: :user, url: password_path(:user), html: { method: :post }, remote: true) do |f| %>
  <div class="single-input">
    <h4><%= t "devise.reset_password.title" %></h4>
  </div>
  <div id="reset_errors">
  </div>
  <div class="single-input">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="single-input">
    <%= f.submit "Send me reset password link" %>
  </div>
<% end %>

app/views/layouts/client/_signup_form.html.erb
<%= form_for(:user, url: user_registration_path, method: :post, remote: true) do |f| %>
  <div id="signup_errors">

  </div>
  <div class="single-input">
    <%= f.text_field :name, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.email_field :email, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.text_field :address, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.text_field :phone, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.password_field :password, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.password_field :password_confirmation, class: "cr-round--lg", placeholder: true %>
  </div>

  <div class="single-input">
    <%= f.submit t("helpers.submit.user.create"), class: "food__btn" %>
  </div>
<% end %>