config/routes.rb
Rails.application.routes.draw do

  root "categories#index"
  post '/rate' => 'rater#create', :as => 'rate'

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions",
    passwords: "passwords",
    confirmations: "confirmations"
  }

  get "/contact", to: "static_pages#contact"

  get "/admin", to: "admin/admins#index"
  get "/welcome", to: "client/clients#index"

  resources :users
  resources :products
  resources :categories

  namespace :admin do
    root "admins#index"
    resources :users
    resources :categories
    resources :products
    resources :orders
  end

  namespace :client do
    root "clients#index"
    resources :carts
    resources :orders, only: [:create, :index]
    resources :rates, only: :create
  end

end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {ready: 0, accepted: 1, delivering: 2, delivered: 3}

  has_many :order_products
  belongs_to :user

  scope :load_orders_by_user, (lambda do |user|
    where user_id: user.id
  end)
  scope :order_by_created_time, ->{order created_at: :desc}

  delegate :name, :address, :phone, to: :user, prefix: :user
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminsController
  before_action :load_order, only: :update
  def index
    @orders = Order.all.order_by_created_time.page(params[:page]).per(
      Settings.paging_sm
    )
  end

  def update
    if @order.update status: Order.statuses[@order.status] + 1
      respond_to do |format|
        format.html{redirect_to admin_orders_path}
        format.js
      end
    else
      flash[:danger] = t "flash.update_fail"
      redirect_to admin_orders_path
    end
  end

  private

  def load_order
    @order = Order.find_by id: params[:id]
    return if @order
    flash[:warning] = t "flash.not_found"
    redirect_to admin_path
  end
end

app/controllers/client/orders_controller.rb
class Client::OrdersController < Client::ClientsController
  before_action :current_order, only: :create

  def index
    @orders = current_user.orders.order_by_created_time.page(params[:page]).per(
      Settings.paging_sm
    )
  end

  def create
    ActiveRecord::Base.transaction do
      create_order
      session[:cart].each do |key, value|
        load_product key
        create_order_product @product, value, @order.id
      end
      session[:cart].clear
      send_order @order
      flash[:success] = t "flash.ordered"
      redirect_to client_orders_path
    end
  rescue ActiveRecord::RecordInvalid
    flash[:warning] = t "flash.rescue_order_creating"
  end

  private

  def create_order
    @order = Order.create(user_id: current_user.id)
    return if @order.save
    flash[:danger] = t "flash.order_faild"
    redirect_to client_carts_path
  end

  def load_product key
    @product = Product.find_by id: key
    return if @product
    flash[:danger] = t "flash.no_longer_sold", name: @product.name
    redirect_to client_carts_path
  end

  def create_order_product product, quantity, order_id
    order_product = OrderProduct.new(
      product_id: product.id,
      quantity: quantity,
      price: product.price,
      order_id: order_id
    )
    return if order_product.save
    flash[:warning] = t "flash.cannot_save"
    redirect_to client_orders_path
  end

  def send_order order
    OrderMailer.new_order(current_admin, current_user, order).deliver_later
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  include MyModules::Orders
  def render_status order
    render "status", order: order
  end

  def render_update_status order
    render "update_status", order: order
  end

  def render_status_label order
    case Order.statuses[order.status]
    when Settings.order_status_ready
      Settings.order_ready_label
    when Settings.order_status_accepted
      Settings.order_accepted_label
    when Settings.order_status_delivering
      Settings.order_delivering_label
    when Settings.order_status_delivered
      Settings.order_delivered_label
    end
  end
end

app/helpers/client/orders_helper.rb
module Client::OrdersHelper
  include MyModules::Orders
end

app/views/admin/orders/_order.html.erb
<tr>
  <td class="" colspan="3">
    <b>
      <%= order.user_name %></b>
  </td>
  <td>
    <div class="update_status" id="update_status<%= order.id %>">
      <%= render_status order %>
    </div>
  </td>
</tr>
  <td colspan="3">
    <table class="product_table">
      <tbody>
        <%= render partial: "order_product", collection: (order.order_products), as: :item %>
      </tbody>
    </table>
  </td>
  <td colspan="1" class="admin_order_info">
    <div class="">
      <%= t "users.new.name" %>: <b><%= order.user_name %></b>
    </div>
    <div class="">
      <%= t "users.new.address" %>: <%= order.user_address %>
    </div>
    <div class="">
      <%= t "users.new.phone" %>: <%= order.user_phone %>
    </div>
  </td>
<tr>
  <td class="" colspan="3">
    <%= t "carts.total" %>:
    <b><%= number_to_currency(load_total_cost order) %></b>
  </td>
</tr>
<tr>
  <td colspan="4" class="blank_row"></td>
</tr>

app/views/admin/orders/_order_product.html.erb
<tr>
  <td class="admin_order_product admin_item">
    <span>- <%= item.product_name %></span>
  </td>
  <td class="admin_order_price admin_item">
    <span><%= item.price %></span>
  </td>
  <td class="admin_order_quantity admin_item">
    <span><%= item.quantity %></span>
  </td>
  <td class="admin_item">
    <span><%= price_of_each_item item.price, item.quantity %></span>
  </td>
</tr>

app/views/admin/orders/_status.html.erb
<%= link_to order.status, admin_order_path(order.id),
  method: :patch, remote: true, class: "btn btn-#{render_status_label order}" %>
at <%= l(order.created_at, format: :short) %>

app/views/admin/orders/index.html.erb
<% provide :title, t("order.order_history") %>

  <div class="cart">
    <div class="page-order">
      <div class="page-title">
        <h2><%= t "order_history" %></h2>
      </div>
      <div class="order-product-content">
        <div class="table-responsive">
          <table class="table table-bordered order_summary">
            <tbody>
              <%= render @orders %>
            </tbody>
          </table>
        </div>
        <div class="row paginate">
          <%= paginate @orders, theme: "twitter-bootstrap-4" %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/orders/update.js.erb
var element = $("#update_status<%= @order.id %>");
element.html('<%= j render "status", order: @order %>');